[package]
name = "bn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mybin"
path = "src/bin.rs"

[dependencies]
# polars = { version = "0.31.1", features=["lazy"] }
rand = "0.8.5"
rayon="1.7.0"